import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainHeader from "./_components/header/MainHeader";
import Wrapper from "./_components/Wrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-transparent h-dvh `}
      >
        <div className=" grid grid-rows-[1fr_auto] h-full">
          <MainHeader />
          <main className="pt-24 bg-primary-50 dark:bg-primary-950 pb-4">
            <Wrapper>{children}</Wrapper>
          </main>
          <footer className="bg-primary-500 dark:bg-primary-800 text-primary-100 p-4">
            <div className="container mx-auto text-center">
              <p>
                &copy; 2024 NextShonen by Yelyzaveta Vlasenko. All rights
                reserved.
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
